version: 2

builds:
  - id: secret-operator-client
    binary: secret-operator-client
    env:
      - CGO_ENABLED=0
    main: cmd/client/main.go
    goos:
      - linux
      - darwin
  - id: secret-operator-server
    binary: secret-operator-server
    env:
      - CGO_ENABLED=0
    main: cmd/server/main.go
    goos:
      - linux
      - darwin

archives:
  - format: binary
    builds:
      - secret-operator-client
      - secret-operator-server
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
